/**
 * @file generate-samples.js
 * Generates sample export files from the rich conversation fixture for inspection.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRichConversationFixture } from '../tests/fixtures/rich-conversation.js';
import * as vectorPdfExporter from '../src/exporters/pdf-vector.js';
import * as docxExporter from '../src/exporters/docx.js';
import * as htmlExporter from '../src/exporters/html.js';
import * as markdownExporter from '../src/exporters/markdown.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SAMPLES_DIR = path.resolve(__dirname, '../dist/samples');

async function blobToBuffer(blob) {
  if (typeof blob.arrayBuffer === 'function') {
    const ab = await blob.arrayBuffer();
    return Buffer.from(ab);
  }
  return Buffer.from(await blob.text());
}

async function run() {
  if (!fs.existsSync(SAMPLES_DIR)) {
    fs.mkdirSync(SAMPLES_DIR, { recursive: true });
  }

  const fixture = createRichConversationFixture();
  console.log('[Samples] Generating rich exports for inspection...');

  // 1. Vector PDF
  const pdfRes = await vectorPdfExporter.exportConversation(fixture, {
    pageFormat: 'a4',
    margin: 'normal',
    fontSize: 10,
    includeToc: true,
    headerText: 'Z.ai Systems & Math Physics Guide',
    footerText: 'Confidential • Generated by Z.ai Chat Exporter'
  });
  const pdfPath = path.join(SAMPLES_DIR, 'sample_rich_export.pdf');
  fs.writeFileSync(pdfPath, await blobToBuffer(pdfRes.blob));
  console.log(`[Samples] ✓ Generated Vector PDF: ${pdfPath} (${(pdfRes.blob.size / 1024).toFixed(1)} KB)`);

  // 2. DOCX
  const docxRes = await docxExporter.exportConversation(fixture);
  const docxPath = path.join(SAMPLES_DIR, 'sample_rich_export.docx');
  fs.writeFileSync(docxPath, await blobToBuffer(docxRes.blob));
  console.log(`[Samples] ✓ Generated DOCX: ${docxPath} (${(docxRes.blob.size / 1024).toFixed(1)} KB)`);

  // 3. Standalone HTML
  const htmlRes = await htmlExporter.exportConversation(fixture);
  const htmlPath = path.join(SAMPLES_DIR, 'sample_rich_export.html');
  fs.writeFileSync(htmlPath, await blobToBuffer(htmlRes.blob));
  console.log(`[Samples] ✓ Generated Standalone HTML: ${htmlPath} (${(htmlRes.blob.size / 1024).toFixed(1)} KB)`);

  // 4. Markdown
  const mdRes = await markdownExporter.exportConversation(fixture, { preset: 'github' });
  const mdPath = path.join(SAMPLES_DIR, 'sample_rich_export.md');
  fs.writeFileSync(mdPath, await blobToBuffer(mdRes.blob));
  console.log(`[Samples] ✓ Generated Markdown: ${mdPath} (${(mdRes.blob.size / 1024).toFixed(1)} KB)`);

  console.log('[Samples] All sample files generated successfully!');
}

run().catch((err) => {
  console.error('[Samples] Generation error:', err);
  process.exit(1);
});
